platform :ios, "9.0"
workspace       "LSYListViewDataSourceDemo"
project "LSYListViewDataSourceDemo.xcodeproj"



target "LSYListViewDataSourceDemo" do
project "LSYListViewDataSourceDemo.xcodeproj"
use_frameworks!

pod 'MJRefresh'
pod 'LSYNetworking'
pod 'YYModel'

end

